2020 refactor
HackSocNotts/hacknotts.com pull request #73
Opened 2020-09-28 15:43 UTC by DanielCordell

Initial refactor, basically looks the same but in gatsby

2020-09-28 15:45 UTC, Emersont1 approved these changes

2020-09-28 16:29 UTC, aaronosher requested changes
Before we merge this, can we get the responsive backgrounds back, please :)

![image](https://user-images.githubusercontent.com/4386583/94460098-26195b80-01b0-11eb-91ad-e8bfb6c33c36.png)

2020-09-28 17:35 UTC, DanielCordell commented
Done :)
![image](https://user-images.githubusercontent.com/16806427/94466479-64ffdf00-01b9-11eb-81d1-178728bda61a.png)

2020-10-02 11:51 UTC, aaronosher approved these changes

2020-10-02 11:52 UTC, merged